language: python

python:
  - "2.7"
  - "3.5"

virtualenv:
  system_site_packages: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get update"

  - "if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then sudo apt-get install -qq hdf5 python-numpy python-scipy python-qt4 python-qt4-gl python-qt4-dev python-sip python-sip-dev python-opengl python-matplotlib; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then sudo apt-get install -qq python3-pyqt4 hdf5; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then sudo apt-get build-dep -qq python3-numpy; fi"

install:
  - "pip install -U --use-mirrors cython"
  - "if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then pip install -U --use-mirrors numpy h5py scipy pyopengl nose matplotlib; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install -U --use-mirrors h5py; fi"
  - "python setup.py build_ext --inplace"
  - "python setup.py install"

script: "nosetests -a '!slow' tests.test_core tests.test_io"
