language: python

python:
  - "2.7"
  - "3.3"

env:
  - NUMPY_VERSION=1.7.1 ONLY_EGG_INFO=false

virtualenv:
  system_site_packages: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get update"
  - "sudo apt-get install -qq python-numpy python-scipy python-pyside python-opengl python-matplotlib"
  - "sudo apt-get install -qq python3-numpy python3-scipy python3-pyside"

install:
  - "pip install -U --use-mirrors cython pyopengl nose matplotlib"
  - "python setup.py build_ext --inplace"
  - "python setup.py install"

script: "nosetests -a '!slow' tests.test_core tests.test_db tests.test_io"
